// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uttqeiidatzdijvczpbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0dHFlaWlkYXR6ZGlqdmN6cGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTc5OTMsImV4cCI6MjA2MTA5Mzk5M30.8NetnJ1swdtGuaPNq4pGrvQF_t_ppX-yupQ1udeWWSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);